name: OpenAmui Build

on:
  - push
  - pull_request

jobs:
  build-openamui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
            bash setup.sh
            bash make.sh
      - name: Upload builded OS 32
        uses: actions/upload-pages-artifact@v3
        with:
          name: openamui-32
          path: ${{ github.workspace }}/build/32/
      - name: Upload builded OS 64
        uses: actions/upload-pages-artifact@v3
        with:
          name: openamui-64
          path: ${{ github.workspace }}/build/64/